Update main.cpp
kevin-koshy/PFMCPP_Project1 pull request #1
Opened 2023-07-12 06:05 UTC by kevin-koshy

Slack username:kevin-koshy

Creating pull request for Project 1

2023-07-12 18:31 UTC, matkatmusic requested changes
you wrote `costMoney()` as an action for 7 out of the 10 exercises.
Try to be more creative on these projects.

2023-07-12 18:31 UTC, matkatmusic commented on main.cpp
> +keyboard.costMoney();
As explained in the instructions:
Here is the obligatory request for some changes to get you familiar with the Pull Request Review process.
REPLACE the highlighted noun/action as follows:
- [ ] come up with a new noun and 3 actions
- [ ] pick a noun that needs `camelCase` for the name
- [ ] pick actions that need `camelCase` for their name.

Do not create an 11th noun.

Once you have completed the above-requested changes, please do the following:
- click each checkbox to mark each requested change as completed.
- click the `[Resolve Conversation]` button.
- Re-request a review of your pull request. It's on the right side of the Pull request page where you originally requested my review.
- Send me the link to your pull request in a new message.

2023-07-12 18:31 UTC, matkatmusic commented on main.cpp
> +lightBulb.costMoney
- [ ] revise: missing `();`

2023-07-13 06:48 UTC, kevin-koshy commented
Updated main.cpp after review

2023-07-13 10:42 UTC, matkatmusic approved these changes

2023-07-13 10:42 UTC, merged